language: ruby
cache: bundler
rvm:
  - 2.1.10
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
  - 2.6.3
  - ruby-head

gemfile:
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile
  - gemfiles/rails_head.gemfile

matrix:
  exclude:
    - rvm: 2.1.10
      gemfile: gemfiles/rails_5.0.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails_5.1.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails_5.2.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails_6.0.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails_head.gemfile
    - rvm: 2.2.9
      gemfile: gemfiles/rails_6.0.gemfile
    - rvm: 2.2.9
      gemfile: gemfiles/rails_head.gemfile
    - rvm: 2.3.6
      gemfile: gemfiles/rails_6.0.gemfile
    - rvm: 2.3.6
      gemfile: gemfiles/rails_head.gemfile
    - rvm: 2.4.3
      gemfile: gemfiles/rails_6.0.gemfile
    - rvm: 2.4.3
      gemfile: gemfiles/rails_head.gemfile
    - rvm: 2.6.3
      gemfile: gemfiles/rails_4.1.gemfile
    - rvm: 2.6.3
      gemfile: gemfiles/rails_4.2.gemfile
    - rvm: 2.6.3
      gemfile: gemfiles/rails_6.0.gemfile
    - rvm: 2.6.3
      gemfile: gemfiles/rails_head.gemfile
  allow_failures:
    - gemfile: gemfiles/rails_head.gemfile
    - rvm: ruby-head

notifications:
  email: false
  slack:
    on_success: change
    on_failure: always
    secure: U/xpgxltcrxFKrV4w0q9PUHu7+WJow8v2hdP2oKYgU4ylfhAbnsmF6rFmzgZPtCt1N1jvO3qydpkSEqh27E4EJ1VDEr76jju3s4292LBBFtneqJx+Lnk4mCHE1NJo1Guyuug8sckP/I/JpDwqgtRgah+vYiley/LMQOVD12xIiQ=
